export const questions = [
    {
      id: 1,
      question: "What is the capital of France?",
      choices: ["Berlin", "Madrid", "Paris", "Rome"],
      correctAnswer: "Paris",
    },
    {
      id: 2,
      question: "Who developed the theory of relativity?",
      choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"],
      correctAnswer: "Albert Einstein",
    },
    {
      id: 3,
      question: "What is the powerhouse of the cell?",
      choices: ["Mitochondria", "Nucleus", "Endoplasmic Reticulum", "Golgi Apparatus"],
      correctAnswer: "Mitochondria",
    },
    {
        id: 4,
        question: "What is the capital of Japan?",
        choices: ["Beijing", "Seoul", "Tokyo", "Bangkok"],
        correctAnswer: "Tokyo",
      },
      {
        id: 5,
        question: "Who wrote 'Romeo and Juliet'?",
        choices: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
        correctAnswer: "William Shakespeare",
      },
      {
        id: 6,
        question: "What is the chemical symbol for gold?",
        choices: ["Au", "Ag", "Fe", "Hg"],
        correctAnswer: "Au",
      },
      {
        id: 7,
        question: "Which planet is known as the 'Red Planet'?",
        choices: ["Earth", "Mars", "Venus", "Jupiter"],
        correctAnswer: "Mars",
      },
      {
        id: 8,
        question: "Who painted the Mona Lisa?",
        choices: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
        correctAnswer: "Leonardo da Vinci",
      },
    {
      id: 9,
      question: "In which year did World War II end?",
      choices: ["1943", "1944", "1945", "1946"],
      correctAnswer: "1945",
    },
    {
        id: 10,
        question: "What is the smallest prime number?",
        choices: ["1", "2", "3", "4"],
        correctAnswer: "2",
      },
      {
        id: 11,
        question: "What is the capital of Brazil?",
        choices: ["Lima", "Buenos Aires", "Brasília", "Santiago"],
        correctAnswer: "Brasília",
      },
      {
        id: 12,
        question: "Who is known as the 'Father of Computers'?",
        choices: ["Alan Turing", "Charles Babbage", "Ada Lovelace", "Bill Gates"],
        correctAnswer: "Charles Babbage",
      },
      {
        id: 13,
        question: "What is the currency of South Korea?",
        choices: ["Yuan", "Won", "Baht", "Ringgit"],
        correctAnswer: "Won",
      },
      {
        id: 14,
        question: "Which gas do plants absorb during photosynthesis?",
        choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
        correctAnswer: "Carbon Dioxide",
      },
      {
        id: 15,
        question: "Who wrote 'To Kill a Mockingbird'?",
        choices: ["J.K. Rowling", "Harper Lee", "George Orwell", "Ernest Hemingway"],
        correctAnswer: "Harper Lee",
      },
      {
        id: 16,
        question: "Which scientist developed the theory of general relativity?",
        choices: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Stephen Hawking"],
        correctAnswer: "Albert Einstein",
      },
      {
        id: 17,
        question: "In which year did the American Civil War end?",
        choices: ["1863", "1865", "1870", "1880"],
        correctAnswer: "1865",
      },
      {
        id: 18,
        question: "What is the largest mammal in the world?",
        choices: ["Elephant", "Giraffe", "Blue Whale", "Hippopotamus"],
        correctAnswer: "Blue Whale",
      },
      {
        id: 19,
        question: "Who discovered penicillin?",
        choices: ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Florence Nightingale"],
        correctAnswer: "Alexander Fleming",
      },
      {
        id: 20,
        question: "What is the chemical symbol for water?",
        choices: ["H2O", "CO2", "O2", "N2"],
        correctAnswer: "H2O",
      },
      {
        id: 21,
        question: "Who painted 'Starry Night'?",
        choices: ["Pablo Picasso", "Vincent van Gogh", "Leonardo da Vinci", "Claude Monet"],
        correctAnswer: "Vincent van Gogh",
      },
      {
        id: 22,
        question: "What is the largest organ in the human body?",
        choices: ["Heart", "Liver", "Brain", "Skin"],
        correctAnswer: "Skin",
      },
      {
        id: 23,
        question: "Which planet is known as the 'Morning Star'?",
        choices: ["Mars", "Venus", "Jupiter", "Saturn"],
        correctAnswer: "Venus",
      },
      {
        id: 24,
        question: "Who is the author of '1984'?",
        choices: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Arthur C. Clarke"],
        correctAnswer: "George Orwell",
      },
      {
        id: 25,
        question: "What is the capital of Australia?",
        choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
        correctAnswer: "Canberra",
      },
      {
        id: 26,
        question: "Which scientist developed the laws of motion and universal gravitation?",
        choices: ["Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Nikola Tesla"],
        correctAnswer: "Isaac Newton",
      },
      {
        id: 27,
        question: "Who developed the theory of evolution by natural selection?",
        choices: ["Charles Darwin", "Gregor Mendel", "Alfred Russel Wallace", "Jean-Baptiste Lamarck"],
        correctAnswer: "Charles Darwin",
      },
      {
        id: 28,
        question: "Which country is known as the Land of the Rising Sun?",
        choices: ["China", "Japan", "South Korea", "Vietnam"],
        correctAnswer: "Japan",
      },
      {
        id: 29,
        question: "In which year did the Berlin Wall fall?",
        choices: ["1985", "1989", "1991", "1995"],
        correctAnswer: "1989",
      },
      {
        id: 30,
        question: "Who wrote 'The Great Gatsby'?",
        choices: ["F. Scott Fitzgerald", "Ernest Hemingway", "J.D. Salinger", "Harper Lee"],
        correctAnswer: "F. Scott Fitzgerald",
      },
      {
        id: 31,
        question: "What is the largest moon in our solar system?",
        choices: ["Io", "Ganymede", "Titan", "Enceladus"],
        correctAnswer: "Ganymede",
      },
      {
        id: 32,
        question: "Who is the author of 'The Catcher in the Rye'?",
        choices: ["J.D. Salinger", "F. Scott Fitzgerald", "Ernest Hemingway", "Mark Twain"],
        correctAnswer: "J.D. Salinger",
      },
      {
        id: 33,
        question: "What is the currency of India?",
        choices: ["Rupiah", "Ringgit", "Rupee", "Baht"],
        correctAnswer: "Rupee",
      },
      {
        id: 34,
        question: "Who discovered the law of gravitation?",
        choices: ["Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Albert Einstein"],
        correctAnswer: "Isaac Newton",
      },
      {
        id: 35,
        question: "Who is the most famous artist from Romania?",
        choices: ["Alexandra Stan", "Nicolae Guta", "Florin Salam", "Inna"],
        correctAnswer: "Inna",
      },
      {
        id: 36,
        question: "(4 + 2) : 2=?",
        choices: ["3", "4", "5", "0"],
        correctAnswer: "3",
      },
      {
        id: 37,
        question: "Who is the most popular team from Romania?",
        choices: ["UTA", "Rapid", "Dinamo", "Steaua"],
        correctAnswer: "Steaua",
      },
      {
        id: 38,
        question: "Who won EURO 2016?",
        choices: ["Portugal", "England", "Italy", "Spain"],
        correctAnswer: "Portugal",
      },
      {
        id: 39,
        question: "What is the capital of Romania?",
        choices: ["Sibiu", "Cluj", "Brasov", "Bucuresti"],
        correctAnswer: "Bucuresti",
      },
      {
        id: 40,
        question: "Who won 2022 World CUP?",
        choices: ["Brazil", "Germany", "France", "Argentina"],
        correctAnswer: "Argentina",
      },

      {
        id: 41,
        question: "Which element has the chemical symbol 'K'?",
        choices: ["Potassium", "Krypton", "Keratin", "Kryptonite"],
        correctAnswer: "Potassium",
      },
      {
        id: 42,
        question: "Who directed the movie 'Inception'?",
        choices: ["Christopher Nolan", "Steven Spielberg", "Quentin Tarantino", "Martin Scorsese"],
        correctAnswer: "Christopher Nolan",
      },
      {
        id: 43,
        question: "What is the primary gas responsible for the greenhouse effect?",
        choices: ["Oxygen", "Methane", "Nitrous Oxide", "Carbon Dioxide"],
        correctAnswer: "Carbon Dioxide",
      },
      {
        id: 44,
        question: "Who was the first woman to win a Nobel Prize?",
        choices: ["Marie Curie", "Rosalind Franklin", "Dorothy Crowfoot Hodgkin", "Barbara McClintock"],
        correctAnswer: "Marie Curie",
      },
      {
        id: 45,
        question: "What is the largest ocean on Earth?",
        choices: ["Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Pacific Ocean"],
        correctAnswer: "Pacific Ocean",
      },
      {
        id: 46,
        question: "What is the largest planet in our solar system?",
        choices: ["Mars", "Earth", "Jupiter", "Saturn"],
        correctAnswer: "Jupiter",
      },
      {
        id: 47,
        question: "Who is known as the 'Queen of Pop'?",
        choices: ["Britney Spears", "Madonna", "Lady Gaga", "Beyoncé"],
        correctAnswer: "Madonna",
      },
      {
        id: 48,
        question: "In which year did the Titanic sink?",
        choices: ["1905", "1912", "1920", "1931"],
        correctAnswer: "1912",
      },
      {
        id: 49,
        question: "What is the largest continent on Earth?",
        choices: ["Africa", "North America", "Asia", "Europe"],
        correctAnswer: "Asia",
      },
      {
        id: 50,
        question: "Who wrote 'The Odyssey'?",
        choices: ["Homer", "Virgil", "Aristotle", "Socrates"],
        correctAnswer: "Homer",
      },
      ];